### PR TITLE
Test improvement

### PR DESCRIPTION
**Pull request by gvma**
This is a test refactoring.

The resource optimism occurs when a test method makes an optimistic assumption that the external resource (e.g., file), utilized by the test method, exists.

As this test presumes the existence of a file that alters the behaviour of tests, It is necessary to ensure this file exists and has content before proceeding with the tests.

### CODE REVIEW

**Comment by gvma** [comment]
@googlebot I signed it!

**Comment by gvma** [comment]
@googlebot I fixed it.

**Comment by gvma** [comment]
@googlebot I signed it!

**Comment by tdeck** [comment]
I'm sorry about the delay on this. This repo is no longer maintained.

I'm declining this PR for the following reasons:

1. It makes unnecessary and unexplained changes to Gradle files
2. It comprises 4 commits that should have been squashed with unclear commit messages
3. The actual "issue" this fixes is not a real issue. If `WebpNativeLibLoader.setDiskLocation()` gets an invalid location the tests will fail anyway because we won't be able to load the associated library.

This looks to me like an automated change. In general I'd caution against submitting automated fixes to random repositories. It's very likely that such changes won't actually be fixing a real problem. Rearranging lines in the Gradle file and changing the Gradle version in an unrelated change are what you might call a "bad smell" in a PR.

**Pull request closed without merging**
